// Audio asset mapping for Expo
// This file maps audio filenames to their require() paths
// Paths are relative to apps/expo/ (where Metro bundler resolves from)
// Auto-generated by CLI - do not edit manually

export const audioAssetMap: Record<string, any> = {
  '4b27ff77-0f9d-4df8-bd58-ad93fcf937a7.mp3': require('./assets/audio/4b27ff77-0f9d-4df8-bd58-ad93fcf937a7.mp3'),
  'ba31eac9-80e5-4abe-b83b-f467d25914de.mp3': require('./assets/audio/ba31eac9-80e5-4abe-b83b-f467d25914de.mp3'),
  '5d0acd9e-15f1-425c-8435-13dcc4fbd6c6.mp3': require('./assets/audio/5d0acd9e-15f1-425c-8435-13dcc4fbd6c6.mp3'),
  '53bc6be7-a26c-43b2-af7a-956b1b430850.mp3': require('./assets/audio/53bc6be7-a26c-43b2-af7a-956b1b430850.mp3'),
  'eb59c21c-c616-4a9b-a042-1e4896684dbb.mp3': require('./assets/audio/eb59c21c-c616-4a9b-a042-1e4896684dbb.mp3'),
  'fdfb77d1-1d75-42f1-bfe8-a9acbf7c6acf.mp3': require('./assets/audio/fdfb77d1-1d75-42f1-bfe8-a9acbf7c6acf.mp3'),
  'aed7c5ae-6247-416d-a560-1d2d59357fff.mp3': require('./assets/audio/aed7c5ae-6247-416d-a560-1d2d59357fff.mp3'),
  '9a6180c6-a032-44fe-abf8-0ee70c0112d3.mp3': require('./assets/audio/9a6180c6-a032-44fe-abf8-0ee70c0112d3.mp3'),
  '9648bd77-fa94-4eab-9c94-08f9a2362678.mp3': require('./assets/audio/9648bd77-fa94-4eab-9c94-08f9a2362678.mp3'),
  '684904a8-df7e-4818-94b1-3f0f04188c82.mp3': require('./assets/audio/684904a8-df7e-4818-94b1-3f0f04188c82.mp3'),
  '9124f674-dba8-470e-b64f-5149548ffdb1.mp3': require('./assets/audio/9124f674-dba8-470e-b64f-5149548ffdb1.mp3'),
  '93f43998-aa3a-460f-a40e-ad2c0b5be4a7.mp3': require('./assets/audio/93f43998-aa3a-460f-a40e-ad2c0b5be4a7.mp3'),
  'f60222e2-09cb-403f-95fc-f988d322a337.mp3': require('./assets/audio/f60222e2-09cb-403f-95fc-f988d322a337.mp3'),
  'ed93da65-a356-489b-b822-f71f5ae55322.mp3': require('./assets/audio/ed93da65-a356-489b-b822-f71f5ae55322.mp3'),
  'b681d9ee-3a3c-4513-b219-4d58bb93803f.mp3': require('./assets/audio/b681d9ee-3a3c-4513-b219-4d58bb93803f.mp3'),
  'b104a968-2e81-4ee7-8535-9887bc3f2ab9.mp3': require('./assets/audio/b104a968-2e81-4ee7-8535-9887bc3f2ab9.mp3'),
  'a4f386d1-dc3f-46c0-bcb9-0000175225b4.mp3': require('./assets/audio/a4f386d1-dc3f-46c0-bcb9-0000175225b4.mp3'),
  '60becab9-dbf3-42b7-8ec6-74b4a8e2d5f6.mp3': require('./assets/audio/60becab9-dbf3-42b7-8ec6-74b4a8e2d5f6.mp3'),
  '6b318ae1-70ee-428a-a3b1-ae5d3c2ee98a.mp3': require('./assets/audio/6b318ae1-70ee-428a-a3b1-ae5d3c2ee98a.mp3'),
  '7bbe1eb1-9869-44ae-926c-fa19511b6754.mp3': require('./assets/audio/7bbe1eb1-9869-44ae-926c-fa19511b6754.mp3'),
  'd2cdd4e8-0d1d-4ff6-9941-6f8461ea0748.mp3': require('./assets/audio/d2cdd4e8-0d1d-4ff6-9941-6f8461ea0748.mp3'),
  '88125eb8-bc33-495c-82c4-3488f0a971ac.mp3': require('./assets/audio/88125eb8-bc33-495c-82c4-3488f0a971ac.mp3'),
  '90df5914-88c6-4f6a-87cb-6ff474ecc974.mp3': require('./assets/audio/90df5914-88c6-4f6a-87cb-6ff474ecc974.mp3'),
  '84068363-936f-4e44-b609-6fa0cb90d7a5.mp3': require('./assets/audio/84068363-936f-4e44-b609-6fa0cb90d7a5.mp3'),
  '91d197d7-a084-4b16-a9bb-0f310de6d1d7.mp3': require('./assets/audio/91d197d7-a084-4b16-a9bb-0f310de6d1d7.mp3'),
  '0677f1b2-4330-4325-a9ff-31a0d0cbaf82.mp3': require('./assets/audio/0677f1b2-4330-4325-a9ff-31a0d0cbaf82.mp3'),
  '57b9ec9e-db73-4dad-9e19-5978a5b52e98.mp3': require('./assets/audio/57b9ec9e-db73-4dad-9e19-5978a5b52e98.mp3'),
  '4d25ef37-1bc3-4b54-a7d3-bd2f4b59e5e4.mp3': require('./assets/audio/4d25ef37-1bc3-4b54-a7d3-bd2f4b59e5e4.mp3'),
  '10b9d59c-620f-4b83-9b06-4ef9e2e6ff1c.mp3': require('./assets/audio/10b9d59c-620f-4b83-9b06-4ef9e2e6ff1c.mp3'),
  'eefe7a29-7210-424e-8a98-77478ae5ad45.mp3': require('./assets/audio/eefe7a29-7210-424e-8a98-77478ae5ad45.mp3'),
}

